/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "facto.h"

void *
facto_null_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

reponse *
facto_res_1_svc(int *argp, struct svc_req *rqstp)
{
	static reponse  result;
	float facto=1;
	result.errno = 0;

	if(*argp<30 && *argp>=0){
		if(*argp>1){
			for(int i=*argp;i>0;i--){
				facto *= i;
			}
			result.facto = facto;
			return &result; 
		}else{
			result.facto = 1;
			return &result;
		}	
	}else{
		result.facto = 0;
		result.errno = 1;	
		return &result;
	}	
}
