/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "facto.h"

bool_t
xdr_reponse (XDR *xdrs, reponse *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->facto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	return TRUE;
}
