/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "facto.h"
#include <unistd.h>

void
facto_1(char *host,int n)
{
	CLIENT *clnt;
	void  *result_1;
	char *facto_null_1_arg;
	reponse  *result_2;
	int  facto_res_1_arg;

	facto_res_1_arg = n;
	printf("Appel de la fonction FACTO_RES avec le paramètre %d\n",n);

#ifndef	DEBUG
	clnt = clnt_create (host, FACTO, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = facto_null_1((void*)&facto_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = facto_res_1(&facto_res_1_arg, clnt);
	if(result_2->errno == 0){
		printf("La factorielle de %d est: %f\n\n",n,result_2->facto);
	}else if(result_2->errno==1){
		printf("La paramètre passé à la fonction doit être positif ou nul et inférieur ou égal à 30\n\n");
	}	
	if (result_2 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	facto_1 (host,22);
	facto_1 (host,-3);
	if(argc>2){facto_1 (host,atoi(argv[2]));}
	exit (0);
}
